### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'motempl' 

### ISSUE THREAD

**Issue by jimin755** [vietdzung/fall-detection-two-stream-cnn#16]
Traceback (most recent call last):
  File "fall_detection.py", line 300, in <module>
    start_fall_detector_realtime("Evening_108(3).mp4")
  File "fall_detection.py", line 210, in start_fall_detector_realtime
    cv.motempl.updateMotionHistory(motion_mask, prev_mhi[prev_ind], prev_timestamp[prev_ind], MHI_DURATION)
AttributeError: module 'cv2.cv2' has no attribute 'motempl'

i install requirements and python3.6 and opencv-contrib-python,opencv-python (4.0.0.21)
plz help me

**Comment by NamanGupta001** [comment]
Hi, you should reinstall your opencv correctly.I used below commands to install it-
pip install opencv-python==3.4.2.17
pip install opencv-contrib-python==3.4.2.17 
It worked for me.Hope it helps
